image: docker:latest

variables:
  DOCKER_DRIVER: overlay

services:
  - docker:dind

before_script:
  - docker info
  - apk add --no-cache curl jq python py-pip
  - apk add --update nodejs nodejs-npm
  - pip install awscli
  - npm install -g serverless
  - npm install serverless-aws-documentation --save-dev
  # install the node js dependencies
  - cd authorizers && npm install && cd ..

stages:
  - deploy

deploy_dev:
  stage: deploy
  script:
    - export AWS_ACCESS_KEY_ID=$DEV_AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$DEV_AWS_SECRET_ACCESS_KEY
    - export SLS_DEBUG=*
    - sls deploy --confile dev --app FracVat --apiKey ${DEV_API_KEY} --partnerId ${DEV_PARTNER_ID}
  environment:
    name: dev
  only:
    - dev